FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache git
RUN git clone https://github.com/Moraaa4/Frontend-RememberMe-d.git .
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
